### ISSUE TITLE
[*] Error -- Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by oppsec** [nstrydom2/anonfile-api#15]
When I try to upload a file I receive this error, I already tried importing requests, json etc but doens't worked

That's my code:
```
file_input = input(Fore.LIGHTRED_EX + " [?] What is the file name? (ex: hello.txt): ")
anon = AnonFile('47d3dxxx...')
file_url = anon.upload_file(file_input)
```

**Comment by nstrydom2** [comment]
Newest release patched this bug. Please verify that this is fixed. This bug occurred because the website has recently changed there URI for their API. I will close this issue as soon as you have verified the bug is fixed.
