### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by jhI1Illou** [nstrydom2/anonfile-api#19]
[*] Error -- ('Connection aborted.', timeout('The write operation timed out')).
i got this error when i try to upload a mp4 files (when the size is 2Mo the problem arrives). I think is a problem with the requests library ? Do you know how can I specify the time to let the upload finish ?
Thanks !

**Comment by nstrydom2** [comment]
I will look into this.

**Comment by chillloouuu** [comment]
Thanks ! Keep me posted.

**Comment by hentai-chan** [comment]
@nstrydom2 I recommend using requests' session object and defining a retry strategy to improve the performance of this library. I used [this blog post](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/#retry-on-failure) as a reference when I encountered a similar problem a while ago.

**Comment by nstrydom2** [comment]
> 
> 
> @nstrydom2 I recommend using requests' session object and defining a retry strategy to improve the performance of this library. I used [this blog post](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/#retry-on-failure) as a reference when I encountered a similar problem a while ago.

Thank you, I have just implemented this solution, and will be uploading the changes. Thank you again.

**Comment by nstrydom2** [comment]
This issue has been resolved in the newest release(v0.1.3)
