### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by hentai-chan** [nstrydom2/anonfile-api#60]
- the upload and download limit caps at around 2MiB/s because of `requests_toolbelt` (see also: this [issue](https://github.com/requests/toolbelt/issues/166))
- the CI script broke some time after [this commit](https://github.com/nstrydom2/anonfile-api/pull/50/commits/ca560da49cb1b92995da9d183353f5ec49a83a17), though the library still seems to work for the most part

**Comment by nstrydom2** [comment]
Seems to be fixed, closing for now.
