### ISSUE TITLE
unsupported operand type(s) for -=: 'tuple' and 'int'

### ISSUE THREAD

**Issue by d4r14h** [nstrydom2/anonfile-api#73]
When I try to upload any file using the CLI (anonfile upload -f 'filename'), it starts the progress bar then fails and says `unsupported operand type(s) for -=: 'tuple' and 'int'`

**Screenshots**
![image](https://user-images.githubusercontent.com/82164005/204880043-3532ffa2-80d5-4501-a8d1-eb082d57e251.png)

**Desktop Information:**
 - OS: Kali GNU/Linux Rolling x86_64
 - Anonfile Version: Latest
 - Kernel: 5.19.0-kali2-amd64
 - Python Version: 3.10.8
 - Terminal: Konsole

`I installed this with pip3 the day of writing this`

**Comment by StefanGreve** [comment]
This error message means that there's a problem on the server side. A similar issue was posted [a while ago](https://github.com/nstrydom2/anonfile-api/issues/71). It would be nice if somebody could catch this case and report a human-readable error message to the user to make things clear.

**Comment by nstrydom2** [comment]
Due to the lack of recent feedback, I am assuming this issue was resolved. If there are further issues regarding this specific error message, then we can reopen this issue and address it. Closing.
