### ISSUE TITLE
not working with FreeBSD

### ISSUE THREAD

**Issue by alma359** [nstrydom2/anonfile-api#83]
Running the command `anonfile --help` on FreeBSD gives the following error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/anonfile", line 5, in <module>
    from anonfile.__init__ import main
  File "/usr/local/lib/python3.8/site-packages/anonfile/__init__.py", line 12, in <module>
    from .anonfile import *
  File "/usr/local/lib/python3.8/site-packages/anonfile/anonfile.py", line 84, in <module>
    file_handler = logging.FileHandler(get_logfile_path())
  File "/usr/local/lib/python3.8/site-packages/anonfile/anonfile.py", line 75, in get_logfile_path
    config_dir = get_config_dir()
  File "/usr/local/lib/python3.8/site-packages/anonfile/anonfile.py", line 65, in get_config_dir
    return {
KeyError: 'FreeBSD'
```

**Comment by nstrydom2** [comment]
I'm pretty sure I know what caused this error. Thank you for bringing it to my attention! I'll look into it tonight.

**Comment by nstrydom2** [comment]
This is caused by a lack of support for 'FreeBSD' based operating systems. However, this shouldn't affect functionality. It will just prevent certain help menus from displaying properly. I will patch this issue before the end of the day.

**Comment by StefanGreve** [comment]
> However, this shouldn't affect functionality

I am not sure about that, the logger configuration on line [84](https://github.com/nstrydom2/anonfile-api/blob/15eca2c27c6bd822d896a0fadb3351b4a28a0e62/src/anonfile/anonfile.py#L84C1-L84C55) should be still invoked when you import this library on a FreeBSD system (which is dependent on the function you identified), so it's definitely a critical error for these users as it prevents them from using this library in any shape or form.

Maybe you can add a fallback value that can be used as a platform-neutral location to prevent similar errors from taking place in the future (though one could still argue that failing silently is dangerous as a concept, but I don't think it's important enough to make this library stop working altogether).

**Comment by nstrydom2** [comment]
Yes, @StefanGreve is correct. The logger configuration is loaded when the logger is initialized. Thus, we get our 'KeyError' type error here when accessing the default location. Rendering the library inert for any users with a different operating system. This is inconvinient, however I pushing a fix now.

We should look into testing some of these environments.

**Comment by nstrydom2** [comment]
Yes, @StefanGreve is correct. The logger configuration is loaded during logger initialization. As a result, when accessing the default location, we encounter a 'KeyError' type error. This issue renders the library ineffective for users with different operating systems, which is inconvenient. However, I am currently working on a fix and will push it soon.

We should consider testing the library in different environments to address these issues.

**Comment by StefanGreve** [comment]
> We should consider testing the library in different environments to address these issues.

Compare PR #86. According to the [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) there are no runners with FreeBSD hosts, but testing for the big 3 platforms should provide sufficient coverage. The vast majority of the code is platform independent, so as long as Python can run, so should this package (with the next release).
